name: Deploy Infrastructure 
on:
  push:
    branches:
      - main

jobs:
  deploy_site:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Execute Terraform in Subdirectories
      run: |
        for dir in terraform/*; do
          if [ -d "$dir" ]; then
            cd $dir
            terraform init
            terraform fmt -check
            terraform validate
            terraform plan
            terraform apply -auto-approve
            cd - 
          fi
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
