name: Deploy Infrastructe 

on: 
  push: 
    branches: 
      - main

permissions: 
  contents: read 
  id-token: write 

jobs: 
  deploy_site: 
    name: Install Ubuntu 
    runs-on: ubuntu-latest 
    defaults: 
      run: 
        working-directory: terraform 

    steps:
    - name: Checkout Repo 
      uses: actions/checkout@v4 
      
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-west-2 
        role-to-assume: arn:aws:iam::213939666921:role/GithubActions
        role-session-name: github-actions

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v2 

    - name: Terraform init 
      run: terraform init 

    - name: Terraform apply 
      run: terraform apply --auto-approve 
